sudo: required
services:
  - docker

before_install:
  - docker build -t jchang006/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true jchang006/docker-react npm run test

deploy:
  - provider: elasticbeanstalk
  - region: "ap-southeast-1"
  - app: "docker-react"
  - env: "DockerReact-env"
  - bucket_name: "elasticbeanstalk-ap-southeast-1-382123691360"
  - bucket_path: "docker-react" # should be the app name by default
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY" 